### PR TITLE
process .js files with babel also, fixes issue with const in dist/rst2html.min.js

### PR DESCRIPTION
**Pull request by DanCech**
The `dist/rst2html.min.js` file currently contains a `const` declaration, which causes issues when included in es5 projects.

This PR modifies the webpack config so that `.js` files are run through babel as well as `.jsx`, so that the output file contains valid es5.

### CODE REVIEW

**Comment by thoward** [comment]
Looks good! Thanks so much for the contribution. I'm just getting started with this project, so there's a lot of loose ends. :)

**Comment by DanCech** [comment]
Happy to help out where I can! I'm looking to use it to integrate function documentation for http://graphiteapp.org/ functions into the UI in https://grafana.com/grafana, you can follow progress at https://github.com/grafana/grafana/pull/10139 if you're interested.

**Comment by thoward** [comment]
Great! I'll follow along. 

One thing to note: This project depends on the parser at https://github.com/seikichi/restructured , which itself is only partially implemented. There are a number of kinds of RST content that are not handled by the parser at all... So, for this renderer to get much better than it is, we'd need to make investments into the parser project.

My next task here will be documenting the code, adding more detailed unit tests, and figuring out where the gaps are in terms of what the parser covers, and what the renderer covers. I also think I'm going to change how the API works, and return a walkable structured tree of tags, with a separate stringify-ing stage, so that things like indents are easier to manage, and to allow folks to walk the tree and add attributes/css classes etc.

**Comment by DanCech** [comment]
any chance you could release 1.0.5?

**Comment by thoward** [comment]
@DanCech I can cut a new release today!

**Pull request merged**
